name: LanguageAPIExamplePlugin
main: me.xhawk87.LanguageAPIExamplePlugin.LanguageAPIExamplePlugin
version: 0.1
soft-depends: [LanguageAPI]

commands:
  wave:
    description: You wave to another player
    usage: /wave [player]
